version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      VIRTUAL_HOST: addressbook.docker
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
