# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fbfb75b04c520b215cec40c6f8bd5421420ecfb2294787721ef2adb12a1b595831ad8bb4e4dd3f070b44bec396c27ad8194535b37bfb095d57d09df619ea559

test:
  secret_key_base: b869b8a07e3c8d5b36082fa194fc676eadb5e3027e0690bfa8773308ed7f71aaaaf12a6fe7a985dccbb827537c51b2b62be1d6ff029851544d2bcb174726ce83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
